import { Link } from "wouter";
import { ArrowUpRight } from "lucide-react";
import { PublicLayout, SectionHeader } from "@/components/SiteLayout";

const principles = [
  ["Flexible, Family-Led Capital", "Funding can be structured across stages, from early conviction through follow-on growth, with decisions made directly by family capital."],
  ["Patient, Long-Term Horizon", "Our timeline is aligned with the real pace of research, development, and commercialization in the sectors we follow."],
  ["Tailor-Made Partnership", "Funding structure, network access, and strategic mentorship are considered in the context of the company, not delivered as a fixed package."],
  ["Fast, Efficient Diligence", "We aim to provide a direct evaluation process with decision cycles that reflect the hands-on nature of a family office."],
  ["Long-Term Alignment", "We look for partners pursuing real technological and sustainable progress, not only the nearest measure of financial growth."],
];

export default function AboutUs() { return <PublicLayout>
  <section className="grid-shell bg-ink px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><p className="label-type text-[10px] text-white/55">About Osmora Capital</p><h1 className="display-type mt-7 max-w-5xl text-6xl font-semibold sm:text-7xl lg:text-9xl">Family capital, <span className="text-white/45">deliberately deployed.</span></h1><p className="mt-10 max-w-2xl text-lg leading-8 text-white/65">Osmora Capital is a family office based in Indonesia, stewarding family financial resources in support of innovation and long-term growth.</p></div></section>
  <section className="bg-paper px-5 py-20 text-ink lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader light eyebrow="Firm Narrative" title={<>Built around <span className="text-ink/45">conviction.</span></>} /><div className="mt-16 grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><p className="label-type text-[10px] text-ink/55">A direct way of working</p><div className="max-w-3xl space-y-7 text-lg leading-8 text-ink/70"><p>Unlike a conventional financial institution, Osmora Capital takes a personal, selective, long-term view. Our work is not simply to deploy capital. It is to build strategic partnerships with the founders and innovators we decide to support.</p><p>For more than a decade, the family behind Osmora Capital has built a practice of wealth stewardship and capital allocation. The firm's investment mandate has been sharpened around five sectors believed to shape the future of Indonesia's economy and the world's.</p><p className="border-l-2 border-ink pl-5 font-medium text-ink">We have intentionally not published individual biographies or portfolio claims here. Partnership conversations should be grounded in the substance of the opportunity.</p></div></div></div></section>
  <section className="bg-charcoal px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader eyebrow="Philosophy & Strengths" title={<>Designed for the <span className="text-white/45">work behind the work.</span></>} /><div className="mt-16 grid border-l border-t border-white/15 md:grid-cols-2 lg:grid-cols-5">{principles.map(([name, copy], index) => <article className="min-h-72 border-b border-r border-white/15 p-5" key={name}><span className="label-type text-[10px] text-white/45">0{index + 1}</span><h2 className="mt-16 text-2xl font-semibold tracking-[-.055em]">{name}</h2><p className="mt-5 text-sm leading-6 text-white/60">{copy}</p></article>)}</div></div></section>
  <section className="bg-smoke px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader eyebrow="Commitment & Governance" title={<>Clear expectations. <span className="text-white/45">Private information.</span></>} /><div className="mt-16 grid gap-8 lg:grid-cols-3"><p className="label-type text-[10px] text-white/50">Draft — pending legal / compliance sign-off</p><p className="text-base leading-7 text-white/65">Osmora Capital aims to communicate clearly about partnership structures, expectations, and governance. Confidential business information shared during evaluation is handled through private systems and used to assess the relevant inquiry or proposal.</p><p className="text-base leading-7 text-white/65">Founders and partners should independently verify any legal status and applicable regulatory requirements with the relevant authorities, including sector-specific regulators and advisers. This explanatory text requires formal legal review before publication.</p></div></div></section>
  <section className="bg-white px-5 py-16 text-ink lg:px-9"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-8 md:flex-row md:items-center"><h2 className="display-type max-w-xl text-5xl font-semibold">A partnership begins with clarity.</h2><Link href="/submit-proposal" className="inline-flex items-center gap-2 bg-ink px-5 py-4 label-type text-[11px] text-white transition hover:bg-smoke">Submit a Proposal <ArrowUpRight size={15} /></Link></div></section>
</PublicLayout>; }
