import { ArrowDownRight, ArrowRight, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { OrbitalNetwork } from "@/components/OrbitalNetwork";
import { PublicLayout, SectionHeader } from "@/components/SiteLayout";
import { faqs, insights, partnershipSteps, sectors } from "@/content/site-data";

export default function Home() {
  return <PublicLayout>
    <section className="noise-overlay grid-shell relative overflow-hidden border-b border-white/15 px-5 pb-16 pt-16 lg:px-9 lg:pb-24 lg:pt-24">
      <div className="absolute right-[13%] top-0 hidden h-28 w-28 bg-smoke lg:block" />
      <div className="absolute bottom-0 left-0 h-8 w-[35%] bg-white/10" />
      <div className="relative mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-[1.1fr_.9fr] lg:gap-20">
        <div>
          <p className="label-type text-[10px] text-white/60">Family Office — Indonesia</p>
          <h1 className="display-type mt-7 max-w-4xl text-[clamp(4.1rem,9vw,9.4rem)] font-semibold text-white">Capital for the <span className="text-white/45">long horizon.</span></h1>
          <p className="mt-9 max-w-xl text-base leading-7 text-white/65 lg:text-lg">Osmora Capital deploys and stewards family financial resources to back innovation and long-term growth—building strategic partnerships with founders working at the frontier.</p>
          <div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/submit-proposal" className="group flex items-center justify-center gap-3 bg-white px-5 py-4 label-type text-[11px] text-ink transition hover:bg-neutral-300">Submit a Proposal <ArrowUpRight size={15} className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link><a href="#focus" className="flex items-center justify-center gap-3 border border-white/35 px-5 py-4 label-type text-[11px] text-white transition hover:border-white hover:bg-white/10">Explore Focus Areas <ArrowDownRight size={15} /></a></div>
        </div>
        <div className="relative"><div className="absolute inset-[12%] bg-smoke/60 blur-3xl" /><OrbitalNetwork /><p className="relative mt-2 text-center label-type text-[9px] text-white/45">Five focus areas / one deliberate mandate</p></div>
      </div>
    </section>

    <section className="bg-paper px-5 py-20 text-ink lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader light eyebrow="The firm" title={<>Personal capital. <span className="text-ink/45">Purposeful partnerships.</span></>} copy="Osmora Capital is a selective family office. We do not operate like a bank, a consumer lender, or a public investment fund. Our work is to identify and support founders whose ambition requires both patient capital and an engaged, long-term counterpart." /><div className="mt-16 grid gap-px bg-ink/20 md:grid-cols-3"><Metric label="Structure" value="Family-led" /><Metric label="Approach" value="Selective" /><Metric label="Horizon" value="Long-term" /></div></div></section>

    <section id="focus" className="bg-charcoal px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader eyebrow="Focus Areas" title={<>The work we choose to <span className="text-white/45">stand behind.</span></>} copy="We have sharpened our mandate around five sectors we believe will shape the future of Indonesia's economy and the world's." /><div className="mt-16 grid border-l border-t border-white/15 md:grid-cols-5">{sectors.map(sector => <Link href="/funding-focus-areas" key={sector.id} className="group min-h-72 border-b border-r border-white/15 p-5 transition hover:bg-paper hover:text-ink"><span className="label-type text-[10px] text-white/45 group-hover:text-ink/45">{sector.number}</span><div className="mt-16"><p className="label-type text-[10px] text-white/55 group-hover:text-ink/55">{sector.abbreviatedName}</p><h3 className="mt-3 text-xl font-semibold tracking-[-.055em]">{sector.name}</h3><p className="mt-4 text-sm leading-6 text-white/55 group-hover:text-ink/65">{sector.thesis}</p></div><ArrowRight className="mt-7 text-white/60 group-hover:text-ink" size={18} /></Link>)}</div><div className="mt-8 text-right"><Link href="/funding-focus-areas" className="industrial-link label-type text-[10px] text-white">View all focus areas</Link></div></div></section>

    <section className="bg-ink px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader eyebrow="Why Osmora Capital" title={<>A different <span className="text-white/45">operating rhythm.</span></>} /><div className="mt-16 grid gap-px bg-white/15 md:grid-cols-2 lg:grid-cols-5">{[["Family capital","Flexible structures shaped around a partnership—not institutional bureaucracy."],["Patient horizon","A pace of capital that respects the real work of R&D-heavy sectors."],["Tailored partnership","Funding structure, network access, and strategic mentorship built for context."],["Efficient diligence","A direct evaluation process designed to move with appropriate conviction."],["Long-term alignment","Partnership with founders pursuing real technological and sustainable progress."]].map(([heading, copy], index) => <article key={heading} className="min-h-56 bg-ink p-5"><span className="label-type text-[10px] text-white/40">0{index + 1}</span><h3 className="mt-11 text-xl font-semibold tracking-[-.055em]">{heading}</h3><p className="mt-4 text-sm leading-6 text-white/55">{copy}</p></article>)}</div></div></section>

    <section className="bg-smoke px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader eyebrow="Partnership Process" title={<>Deliberate from <span className="text-white/45">first contact.</span></>} copy="A structured path provides clarity while leaving room for the particulars of each company and opportunity." /><div className="mt-16 grid gap-px bg-white/15 lg:grid-cols-5">{partnershipSteps.map(([number, name, copy]) => <article key={number} className="bg-smoke p-5"><p className="label-type text-[10px] text-white/50">{number}</p><h3 className="mt-10 text-xl font-semibold tracking-[-.05em]">{name}</h3><p className="mt-4 text-sm leading-6 text-white/55">{copy}</p></article>)}</div><div className="mt-8"><Link href="/our-offer" className="industrial-link label-type text-[10px]">See the full process</Link></div></div></section>

    <section className="bg-paper px-5 py-20 text-ink lg:px-9 lg:py-28"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-[.6fr_1.4fr]"><div><p className="label-type text-[10px] text-ink/55">FAQ</p><h2 className="display-type mt-6 text-5xl font-semibold sm:text-6xl">Questions, <span className="text-ink/45">answered directly.</span></h2><p className="mt-7 max-w-sm text-sm leading-6 text-ink/65">Start with the essentials of Osmora Capital's focus, partnership approach, and proposal process.</p><Link href="/faq" className="mt-8 inline-block bg-ink px-5 py-4 label-type text-[10px] text-white transition hover:bg-smoke">View Full FAQ</Link></div><div className="border-t border-ink/25">{faqs.slice(0, 3).map(([question, answer]) => <article key={question} className="border-b border-ink/25 py-6"><h3 className="text-xl font-semibold tracking-[-.045em]">{question}</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/65">{answer}</p></article>)}</div></div></section>

    <section className="bg-paper px-5 py-20 text-ink lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader light eyebrow="Perspectives" title={<>Notes from a <span className="text-ink/45">long view.</span></>} copy="A selected reading list across frontier investment, deep-tech funding, governance, and the family-office perspective." /><div className="mt-16 grid gap-5 lg:grid-cols-3">{insights.map(([category, title, copy], index) => <article key={title} className={`min-h-72 p-6 ${index === 1 ? "bg-ink text-white" : "bg-silver"}`}><p className={`label-type text-[10px] ${index === 1 ? "text-white/50" : "text-ink/55"}`}>{category}</p><h3 className="mt-16 max-w-sm text-3xl font-semibold tracking-[-.06em]">{title}</h3><p className={`mt-5 text-sm leading-6 ${index === 1 ? "text-white/60" : "text-ink/65"}`}>{copy}</p></article>)}</div><div className="mt-8 text-right"><Link href="/blog" className="industrial-link label-type text-[10px]">See all perspectives</Link></div></div></section>

    <section className="border-y border-white/15 bg-ink px-5 py-12 lg:px-9"><div className="mx-auto grid max-w-[1500px] gap-8 lg:grid-cols-[.5fr_1.5fr]"><p className="label-type text-[10px] text-white/55">Partner Sentiment</p><p className="max-w-4xl text-2xl leading-tight tracking-[-.045em] text-white/80 sm:text-3xl">Founders and partners we have worked with consistently point to a personal approach, transparent evaluation process, and long-term support that goes beyond capital.</p></div></section>
    <section className="bg-white px-5 py-20 text-ink lg:px-9 lg:py-28"><div className="mx-auto grid max-w-[1500px] items-end gap-8 lg:grid-cols-[1.25fr_.75fr]"><div><p className="label-type text-[10px] text-ink/55">Start a conversation</p><h2 className="display-type mt-6 max-w-4xl text-6xl font-semibold sm:text-7xl lg:text-8xl">Building on the frontier?</h2></div><div><p className="max-w-md text-base leading-7 text-ink/65">If your work belongs in AI, Biotech, Space, Renewable Energy, or Blockchain & Crypto, we would like to understand the opportunity.</p><Link href="/submit-proposal" className="mt-7 inline-flex items-center gap-3 bg-ink px-5 py-4 label-type text-[11px] text-white transition hover:bg-smoke">Submit a Proposal <ArrowUpRight size={15} /></Link></div></div></section>
  </PublicLayout>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-paper p-5 sm:p-7"><p className="label-type text-[10px] text-ink/55">{label}</p><p className="mt-10 text-3xl font-semibold tracking-[-.06em]">{value}</p></div>; }
