import { Link } from "wouter";
import { ArrowUpRight } from "lucide-react";
import { PublicLayout, SectionHeader } from "@/components/SiteLayout";
import { partnershipSteps } from "@/content/site-data";

export default function OurOffer() { return <PublicLayout>
  <section className="grid-shell bg-ink px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><p className="label-type text-[10px] text-white/55">Our Offer</p><h1 className="display-type mt-7 max-w-5xl text-6xl font-semibold sm:text-7xl lg:text-9xl">More than the <span className="text-white/45">capital stack.</span></h1><p className="mt-10 max-w-2xl text-lg leading-8 text-white/65">Partnership can include tailored funding structures, network access, and strategic mentorship from the family and its partners.</p></div></section>
  <section className="bg-paper px-5 py-20 text-ink lg:px-9 lg:py-28"><div className="mx-auto max-w-[1500px]"><SectionHeader light eyebrow="Partnership & Funding Process" title={<>A sequence with <span className="text-ink/45">purpose.</span></>} copy="These five steps create a shared frame for moving from an initial proposal to a long-term relationship." /><div className="mt-16">{partnershipSteps.map(([number, name, copy], index) => <article key={number} className="grid gap-5 border-t border-ink/25 py-8 lg:grid-cols-[.25fr_.55fr_1.2fr] lg:items-start"><span className="label-type text-[11px] text-ink/55">{number}</span><h2 className="text-3xl font-semibold tracking-[-.06em]">{name}</h2><p className="max-w-2xl text-base leading-7 text-ink/65">{copy}</p><span className="hidden lg:block label-type text-[10px] text-right text-ink/40">{String(index + 1).padStart(2, "0")} / 05</span></article>)}</div></div></section>
  <section className="bg-charcoal px-5 py-20 lg:px-9 lg:py-28"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-[.75fr_1.25fr]"><p className="label-type text-[10px] text-white/50">What a partner receives</p><div><h2 className="display-type max-w-4xl text-5xl font-semibold sm:text-6xl">A counterpart committed to the <span className="text-white/45">next decision.</span></h2><p className="mt-8 max-w-2xl text-base leading-7 text-white/65">We consider the funding structure, the relevant network, and practical strategic support together. The objective is not a standardized transaction; it is an approach matched to the company and its horizon.</p></div></div></section>
  <section className="bg-white px-5 py-16 text-ink lg:px-9"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-8 md:flex-row md:items-center"><h2 className="display-type text-5xl font-semibold">Ready to build with us?</h2><Link href="/submit-proposal" className="inline-flex items-center gap-2 bg-ink px-5 py-4 label-type text-[11px] text-white hover:bg-smoke">Submit a Proposal <ArrowUpRight size={15} /></Link></div></section>
</PublicLayout>; }
